#!/usr/bin/env python3.5

from apiclient.discovery import build
from httplib2 import Http
from oauth2client import file, client, tools
import googleapiclient
import argparse
import pyperclip
import pathlib
import sys


def parse_args():
    parse = argparse.ArgumentParser(parents=[tools.argparser])
    parse.add_argument('file', help='file to upload', type=str)
    args = parse.parse_args()
    return args


def setup_api(args):
    SCOPES = 'https://www.googleapis.com/auth/drive'
    store = file.Storage(
        '{}/.gpush/credentials.json'.format(pathlib.Path.home()))
    creds = store.get()
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets(
            '{}/.gpush/client_secret.json'.format(pathlib.Path.home()), SCOPES)
        creds = tools.run_flow(flow, store, args)
    return build('drive', 'v3', http=creds.authorize(Http()))


def get_push_folder(service):
    folder = service.files().list(
        q="name='GPush'",
        pageSize=100,
        fields="files(id, mimeType)"
    ).execute()
    for obj in folder.get('files'):
        if obj.get('mimeType') == 'application/vnd.google-apps.folder':
            return obj.get('id')

    return service.files().create(
        body={
            'name': 'GPush',
            'mimeType': 'application/vnd.google-apps.folder',
        },
        fields='id',
    ).execute().get('id')


def push_file(service, file, folder_id):
    filepath = file
    filename = filepath.split('/')[-1]
    media = googleapiclient.http.MediaFileUpload(filepath)
    file = service.files().create(
        body={
            'name': filename,
            'originalFilename': filepath,
            'parents': [folder_id],
        },
        media_body=media,
        fields='id,webContentLink',
    ).execute()

    batch = service.new_batch_http_request()
    batch.add(service.permissions().create(
        fileId=file.get('id'),
        body={
            'type': 'anyone',
            'role': 'reader',
        },
        fields='',
    ))
    batch.execute()
    return file


def main():
    pathlib.Path('{}/.gpush'.format(pathlib.Path.home())
                 ).mkdir(parents=True, exist_ok=True)
    args = parse_args()
    try:
        service = setup_api(args)
    except Exception as e:
        print(e, file=sys.stderr, end='\n\n')
        print("Seems you did'nt configure the Google API. Please read the README.md file!", file=sys.stderr)
        exit(1)
    folder_id = get_push_folder(service)
    file = push_file(service, args.file, folder_id)
    print(file.get('webContentLink'))
    pyperclip.copy(file.get('webContentLink'))
    print('Link copied!')


if __name__ == '__main__':
    main()
